# Generated by Django 2.1.2 on 2018-10-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xssw', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xssurl',
        ),
    ]
