# Generated by Django 2.1.2 on 2018-10-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xssw', '0003_xssurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xssurl',
        ),
    ]
